name: Jira Group Users

on:
  workflow_dispatch:
    inputs:
      projectKey:
        description: "Project key from Atlassian Automation (e.g. ABC)"
        required: true
      issueKey:
        description: "Jira issue key to comment on (e.g. ABC-123)"
        required: true

jobs:
  retrieve-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      # DEBUG STEP: print environment variables to confirm they are set
      - name: Debug environment variables
        run: |
          echo "PROJECT_KEY => ${PROJECT_KEY}"
          echo "ISSUE_KEY => ${ISSUE_KEY}"
          
          echo "BASIC_AUTH => ${BASIC_AUTH}"
          echo "Length of BASIC_AUTH => ${#BASIC_AUTH}"
          
          # (Optional) If you'd prefer not to print the token, 
          # you can show a partial snippet or only the length.
        env:
          PROJECT_KEY: ${{ github.event.inputs.projectKey }}
          ISSUE_KEY: ${{ github.event.inputs.issueKey }}
          BASIC_AUTH: ${{ secrets.JIRA_BASIC_AUTH }}

      - name: Run script
        run: python .github/workflows/jira_group_users.py
        env:
          PROJECT_KEY: ${{ github.event.inputs.projectKey }}
          ISSUE_KEY: ${{ github.event.inputs.issueKey }}

          # Note: This must match EXACTLY the variable name your Python script expects.
          # If the script uses os.environ.get("BASIC_AUTH"), keep this as BASIC_AUTH.
          BASIC_AUTH: ${{ secrets.JIRA_BASIC_AUTH }}
