name: Jira Group Users

on:
  repository_dispatch:
    types: [jira_group_users]

jobs:
  retrieve-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script to get users and post comment
        run: python .github/workflows/jira_group_users.py
        env:
          PROJECT_KEY: ${{ github.event.client_payload.projectKey }}
          ISSUE_KEY: ${{ github.event.client_payload.issueKey }}
          BASIC_AUTH: ${{ secrets.JIRA_BASIC_AUTH }}
          JIRA_SITE: "https://prudential-ps.atlassian.net"
