name: Restore User Access

on:
  repository_dispatch:
    types: [restore-user]

jobs:
  restore_user:
    runs-on: ubuntu-latest
    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_ISSUE_KEY: ${{ github.event.client_payload.jira_issue_key }}
      TARGET_EMAIL: ${{ github.event.client_payload.target_email }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Debug Environment Variables
        run: |
          echo "JIRA_BASE_URL: $(echo -n $JIRA_BASE_URL | base64)"
          echo "USERNAME: $(echo -n $JIRA_USERNAME | base64)"
          echo "TOKEN LENGTH: ${#JIRA_API_TOKEN}"
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Run restore user script
        run: python .github/workflows/restore_user.py
        env:
          TARGET_EMAIL: ${{ env.TARGET_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}

      - name: Update Jira ticket with result
        run: |
          RESULT=$(cat result.txt)
          echo "Original RESULT:"
          echo "$RESULT"
          
          # Remove all ANSI escape sequences (including OSC hyperlink sequences) using Perl
          CLEAN_RESULT=$(echo "$RESULT" | perl -pe 's/\e\]8;;.*?\e\\//g; s/\e\[[0-9;]*[a-zA-Z]//g')
          echo "Cleaned RESULT:"
          echo "$CLEAN_RESULT"
          
          # Replace the raw URL with the Jira Wiki-style link.
          # Use '#' as delimiter so that slashes and pipes are not interpreted.
          FORMATTED_RESULT=$(echo "$CLEAN_RESULT" | sed "s#https://prudential-ps.atlassian.net/servicedesk/customer/portal/6/group/10/create/44#[log a ticket|https://prudential-ps.atlassian.net/servicedesk/customer/portal/6/group/10/create/44]#g")
          echo "Final FORMATTED_RESULT:"
          echo "$FORMATTED_RESULT"
          
          # Build the JSON payload using the Atlassian Document Format for comments.
          COMMENT_JSON=$(jq -n --arg msg "$FORMATTED_RESULT" '{
            "update": {
              "comment": [{
                "add": {
                  "body": {
                    "type": "doc",
                    "version": 1,
                    "content": [
                      {
                        "type": "paragraph", 
                        "content": [
                          {"type": "text", "text": $msg}
                        ]
                      }
                    ]
                  }
                }
              }]
            }
          }')
          
          echo "Final JSON Payload:"
          echo "$COMMENT_JSON"
          
          curl -X PUT -u "${JIRA_USERNAME}:${JIRA_API_TOKEN}" \
            -H "Content-Type: application/json" \
            --data "$COMMENT_JSON" \
            "${JIRA_BASE_URL}/rest/api/3/issue/${JIRA_ISSUE_KEY}"
        env:
          JIRA_BASE_URL: ${{ env.JIRA_BASE_URL }}
          JIRA_USERNAME: ${{ env.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ env.JIRA_API_TOKEN }}
          JIRA_ISSUE_KEY: ${{ env.JIRA_ISSUE_KEY }}








