name: Restore User Access

on:
  repository_dispatch:
    types: [restore-user]

jobs:
  restore_user:
    runs-on: ubuntu-latest
    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_BASIC_TOKEN: ${{ secrets.JIRA_BASIC_TOKEN }}
      JIRA_BEARER_TOKEN: ${{ secrets.JIRA_BEARER_TOKEN }}
      JIRA_ISSUE_KEY: ${{ github.event.client_payload.jira_issue_key }}
      TARGET_EMAIL: ${{ github.event.client_payload.target_email }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Debug Environment Variables
        run: |
          echo "JIRA_BASE_URL: $(echo -n $JIRA_BASE_URL | base64)"
          echo "Basic Token Length: ${#JIRA_BASIC_TOKEN}"
          echo "Bearer Token Length: ${#JIRA_BEARER_TOKEN}"
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_BASIC_TOKEN: ${{ secrets.JIRA_BASIC_TOKEN }}
          JIRA_BEARER_TOKEN: ${{ secrets.JIRA_BEARER_TOKEN }}

      - name: Run restore user script
        id: run_script
        run: |
          OUTPUT=$(python .github/workflows/restore_user.py)
          echo "result=$OUTPUT" >> $GITHUB_OUTPUT
        env:
          TARGET_EMAIL: ${{ env.TARGET_EMAIL }}
          JIRA_BASIC_TOKEN: ${{ secrets.JIRA_BASIC_TOKEN }}
          JIRA_BEARER_TOKEN: ${{ secrets.JIRA_BEARER_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}

      - name: Update Jira ticket with result
        run: |
          RESULT="${{ steps.run_script.outputs.result }}"
          echo "Updating Jira ticket ${JIRA_ISSUE_KEY} with result:"
          echo "${RESULT}"
          
          COMMENT_JSON=$(jq -n --arg msg "$RESULT" '{
            "update": {
              "comment": [{
                "add": {
                  "body": {
                    "type": "doc",
                    "version": 1,
                    "content": [
                      {
                        "type": "paragraph", 
                        "content": [
                          {"type": "text", "text": $msg}
                        ]
                      }
                    ]
                  }
                }
              }]
            }
          }')
          
          echo "Final JSON Payload:"
          echo "$COMMENT_JSON"
          
          curl -X PUT -H "Content-Type: application/json" \
            -H "Authorization: Basic ${JIRA_BASIC_TOKEN}" \
            --data "$COMMENT_JSON" \
            "${JIRA_BASE_URL}/rest/api/3/issue/${JIRA_ISSUE_KEY}"
        env:
          JIRA_BASE_URL: ${{ env.JIRA_BASE_URL }}
          JIRA_BASIC_TOKEN: ${{ env.JIRA_BASIC_TOKEN }}
          JIRA_ISSUE_KEY: ${{ env.JIRA_ISSUE_KEY }}
